Problems & Solutions/1071. Greatest Common Divisor of Strings/01 February 2023/Approach 1 - Brute Force/Greatest Common Divisor of Strings.cpp, Problems & Solutions/1071. Greatest Common Divisor of Strings/01 February 2023/Approach 1 - Brute Force/Greatest Common Divisor of Strings.java, Problems & Solutions/1071. Greatest Common Divisor of Strings/01 February 2023/Approach 1 - Brute Force/Greatest Common Divisor of Strings.py, Problems & Solutions/1071. Greatest Common Divisor of Strings/01 February 2023/Approach 2 - Greatest Common Divisor/Greatest Common Divisor of Strings.cpp, Problems & Solutions/1071. Greatest Common Divisor of Strings/01 February 2023/Approach 2 - Greatest Common Divisor/Greatest Common Divisor of Strings.java, Problems & Solutions/1071. Greatest Common Divisor of Strings/01 February 2023/Approach 2 - Greatest Common Divisor/Greatest Common Divisor of Strings.py, Problems & Solutions/1071. Greatest Common Divisor of Strings/01 February 2023/README.md, Problems & Solutions/1137. N-th Tribonacci Number/30 January 2023/README.md
Closes #196 
Closes #197  
Closes #198
=> 1071. Greatest Common Divisor of Strings - 01 February 2023

.github/pull_request_template.md, Problems & Solutions/1071. Greatest Common Divisor of Strings/01 February 2023/README.md, Problems & Solutions/953. Verifying an Alien Dictionary/02 February 2023/Approach 1 - Compare adjacent words/Verifying an Alien Dictionary.java, Problems & Solutions/953. Verifying an Alien Dictionary/02 February 2023/Approach 1 - Compare adjacent words/Verifying an Alien Dictionary.py, Problems & Solutions/953. Verifying an Alien Dictionary/02 February 2023/README.md
Closes #229 
Closes #231 
Closes #232
=> 953. Verifying an Alien Dictionary - 02 February 2023

Problems & Solutions/953. Verifying an Alien Dictionary/02 February 2023/Approach 1 - Compare adjacent words/Verifying an Alien Dictionary.cpp
=> 2Feb C++ code added

Problems & Solutions/6. Zigzag Conversion/03 February 2023/Approach 1 - Simulate Zig-Zag Movement/Zigzag Conversion.cpp, Problems & Solutions/6. Zigzag Conversion/03 February 2023/Approach 1 - Simulate Zig-Zag Movement/Zigzag Conversion.java, Problems & Solutions/6. Zigzag Conversion/03 February 2023/Approach 1 - Simulate Zig-Zag Movement/Zigzag Conversion.js, Problems & Solutions/6. Zigzag Conversion/03 February 2023/Approach 1 - Simulate Zig-Zag Movement/Zigzag Conversion.py, Problems & Solutions/6. Zigzag Conversion/03 February 2023/Approach 2 - String Traversal/Zigzag Conversion.cpp, Problems & Solutions/6. Zigzag Conversion/03 February 2023/Approach 2 - String Traversal/Zigzag Conversion.java, Problems & Solutions/6. Zigzag Conversion/03 February 2023/Approach 2 - String Traversal/Zigzag Conversion.js, Problems & Solutions/6. Zigzag Conversion/03 February 2023/Approach 2 - String Traversal/Zigzag Conversion.py, Problems & Solutions/6. Zigzag Conversion/03 February 2023/README.md
Closes #239 
Closes #240 
Closes #241 
Closes #242 
Closes #243
=> 03 February 2023

Problems & Solutions/567. Permutation in String/04 February 2023/Approach 1 - Brute Force/Short Permutation in a Long String.java, Problems & Solutions/567. Permutation in String/04 February 2023/Approach 2 - Using sorting/Short Permutation in a Long String.java, Problems & Solutions/567. Permutation in String/04 February 2023/Approach 3 - Using Hashmap/Short Permutation in a Long String.java, Problems & Solutions/567. Permutation in String/04 February 2023/Approach 4 - Using Array [Accepted]/Short Permutation in a Long String.java, Problems & Solutions/567. Permutation in String/04 February 2023/Approach 5 - Sliding Window [Accepted]/Short Permutation in a Long String.java, Problems & Solutions/567. Permutation in String/04 February 2023/Approach 6 - Optimized Sliding Window [Accepted]/Short Permutation in a Long String.java, Problems & Solutions/567. Permutation in String/04 February 2023/README.md
=> 04 February 2023

Problems & Solutions/438. Find All Anagrams in a String/05 February 2023/Find All Anagrams in a String.cpp, Problems & Solutions/438. Find All Anagrams in a String/05 February 2023/README.md
=> 05 February 2023

Problems & Solutions/904. Fruit Into Baskets/07 February 2023/Approach 1 - Brute Force/Fruit Into Baskets.cpp, Problems & Solutions/904. Fruit Into Baskets/07 February 2023/Approach 1 - Brute Force/Fruit Into Baskets.java, Problems & Solutions/904. Fruit Into Baskets/07 February 2023/Approach 1 - Brute Force/Fruit Into Baskets.py, Problems & Solutions/904. Fruit Into Baskets/07 February 2023/README.md
Closes #257 
Closes #258 
Closes #259 
Closes #260
=> 07 February 2023 - Approach 1 - Brute Force

Problems & Solutions/45. Jump Game II/08 February 2023/Approach 1 - Greedy/Jump Game II.cpp, Problems & Solutions/45. Jump Game II/08 February 2023/Approach 1 - Greedy/Jump Game II.java, Problems & Solutions/45. Jump Game II/08 February 2023/Approach 1 - Greedy/Jump Game II.py, Problems & Solutions/45. Jump Game II/08 February 2023/README.md
Closes #273 
Closes #274 
Closes #275 
Closes #276
=> 08 February 2023 - Approach 1 - Greedy

Problems & Solutions/2306. Naming a Company/09 February 2023/Approach 1 - Group words by their initials/Naming a Company.java, Problems & Solutions/2306. Naming a Company/09 February 2023/Approach 1 - Group words by their initials/Naming a Company.py
=> 09 February 2023 - Approach 1 - Group words by their initials

Problems & Solutions/1129. Shortest Path with Alternating Colors/11 February 2023/Approach - Breadth First Search/Shortest Path with Alternating Colors.cpp, Problems & Solutions/1129. Shortest Path with Alternating Colors/11 February 2023/README.md, Problems & Solutions/1162. As Far from Land as Possible/10 February 2023/Approach 1 - Breadth-First Search (BFS)/As Far from Land as Possible.cpp, Problems & Solutions/1162. As Far from Land as Possible/10 February 2023/README.md, Problems & Solutions/1523. Count Odd Numbers in an Interval Range/13 February 2023/Approach 1 - Maths/Count Odd Numbers in an Interval Range.cpp, Problems & Solutions/1523. Count Odd Numbers in an Interval Range/13 February 2023/Approach 1 - Maths/Count Odd Numbers in an Interval Range.java, Problems & Solutions/1523. Count Odd Numbers in an Interval Range/13 February 2023/README.md, Problems & Solutions/2477. Minimum Fuel Cost to Report to the Capital/12 February 2023/Approach 1 - Depth First Search/Minimum Fuel Cost to Report to the Capital.cpp, Problems & Solutions/2477. Minimum Fuel Cost to Report to the Capital/12 February 2023/Approach 1 - Depth First Search/README.md
Closes #284 
Closes #285 
Closes #286 
Closes #288 
Closes #289 
Closes #281 
Closes #282 
Closes #283 
Closes #287
=> 10, 11, 12, 13 February 2023

Problems & Solutions/67. Add Binary/14 February 2023/Add Binary.java, Problems & Solutions/67. Add Binary/14 February 2023/README.md
=> 67. Add Binary - 14 February 2023

Problems & Solutions/989. Add to Array-Form of Integer/15 February 2023/Approach 1 - Schoolbook Addition/Add to Array-Form of Integer.java, Problems & Solutions/989. Add to Array-Form of Integer/15 February 2023/README.md
=> 989. Add to Array-Form of Integer - 15 February 2023

Problems & Solutions/104. Maximum Depth of Binary Tree/16 February 2023/Maximum Depth of Binary Tree.cpp, Problems & Solutions/104. Maximum Depth of Binary Tree/16 February 2023/README.md
=> 104. Maximum Depth of Binary Tree - 16 February 2023

Problems & Solutions/783. Minimum Distance Between BST Nodes/17 February 2023/Approach 1 - In-order Traversal with List/Minimum Distance Between BST Nodes.cpp, Problems & Solutions/783. Minimum Distance Between BST Nodes/17 February 2023/README.md
17 February 2023 - Approach 1 - In-order Traversal with List
Closes #300 
Closes #301
=> 783. Minimum Distance Between BST Nodes

Problems & Solutions/226. Invert Binary Tree/18 February 2023/Approach 1 - Recursive/Invert Binary Tree.java, Problems & Solutions/226. Invert Binary Tree/18 February 2023/README.md
226. Invert Binary Tree - 18 February 2023 - Approach 1 - Recursive
Closes #
=> 18 February 2023

Problems & Solutions/103. Binary Tree Zigzag Level Order Traversal/19 February 2023/Binary Tree Zigzag Level Order Traversal.java, Problems & Solutions/103. Binary Tree Zigzag Level Order Traversal/19 February 2023/README.md
103. Binary Tree Zigzag Level Order Traversal - 19 February 2023
Closes #306 
Closes #308
=> 19 February 2023

Problems & Solutions/35. Search Insert Position/20 February 2023/README.md, Problems & Solutions/35. Search Insert Position/20 February 2023/Search Insert Position.java
=> 35. Search Insert Position - 20 February 2023

Problems & Solutions/1011. Capacity To Ship Packages Within D Days/22 February 2023/Approach - Binary Search/Capacity To Ship Packages Within D Days.java, Problems & Solutions/1011. Capacity To Ship Packages Within D Days/22 February 2023/README.md, Problems & Solutions/35. Search Insert Position/20 February 2023/README.md, Problems & Solutions/540. Single Element in a Sorted Array/21 February 2023/README.md, Problems & Solutions/540. Single Element in a Sorted Array/21 February 2023/Single Element in a Sorted Array.java
Closes #321 
Closes #322 
Closes #323 
Closes #324
=> 21 & 22 February 2023

Problems & Solutions/502. IPO/23 February 2023/README.md
=> 502. IPO - 23 February 2023

Problems & Solutions/1675. Minimize Deviation in Array/24 February 2023/Minimize Deviation in Array.java, Problems & Solutions/1675. Minimize Deviation in Array/24 February 2023/README.md, Problems & Solutions/502. IPO/23 February 2023/README.md
updated 502. IPO - 23 February 2023
Closes #329 
Closes #330
=> 1675. Minimize Deviation in Array - 24 February 2023

Problems & Solutions/121. Best Time to Buy and Sell Stock/25 February 2023/Best Time to Buy and Sell Stock.cpp, Problems & Solutions/121. Best Time to Buy and Sell Stock/25 February 2023/README.md, Problems & Solutions/72. Edit Distance/26 February 2023/Edit Distance.cpp, Problems & Solutions/72. Edit Distance/26 February 2023/README.md
Closes #332 
Closes #333 
Closes #334 
Closes #335
=> 25 & 26 February 2023

Problems & Solutions/427. Construct Quad Tree/27 February 2023/Construct Quad Tree.java, Problems & Solutions/427. Construct Quad Tree/27 February 2023/README.md, Problems & Solutions/652. Find Duplicate Subtrees/28 February 2023/Find Duplicate Subtrees.cpp, Problems & Solutions/652. Find Duplicate Subtrees/28 February 2023/README.md
Closes #347 
Closes #348 
Closes #349 
Closes #350
=> 27 & 28 February 2023

Problems & Solutions/443. String Compression/02 March 2023/README.md, Problems & Solutions/443. String Compression/02 March 2023/String Compression.cpp, Problems & Solutions/912. Sort an Array/01 March 2023/README.md, Problems & Solutions/912. Sort an Array/01 March 2023/Sort an Array.cpp
Closes #354 
Closes #355 
Closes #356 
Closes #357
=> 01 & 02 March 2023

Problems & Solutions/28. Find the Index of the First Occurrence in a String/03 March 2023/Find the Index of the First Occurrence in a String.java, Problems & Solutions/28. Find the Index of the First Occurrence in a String/03 March 2023/README.md
=> 03 March 2023

Problems & Solutions/2444. Count Subarrays With Fixed Bounds/04 March 2023/Count Subarrays With Fixed Bounds.java, Problems & Solutions/2444. Count Subarrays With Fixed Bounds/04 March 2023/README.md
=> 04 March 2023

Problems & Solutions/1345. Jump Game IV/05 March 2023/Jump Game IV.java, Problems & Solutions/1345. Jump Game IV/05 March 2023/README.md
=> 05 March 2023

Problems & Solutions/1539. Kth Missing Positive Number/06 March 2023/Kth Missing Positive Number.java, Problems & Solutions/1539. Kth Missing Positive Number/06 March 2023/README.md
=> 06 March 2023

Problems & Solutions/2187. Minimum Time to Complete Trips/07 March 2023/Minimum Time to Complete Trips.java, Problems & Solutions/2187. Minimum Time to Complete Trips/07 March 2023/README.md
=> 07 March 2023

Problems & Solutions/142. Linked List Cycle II/09 March 2023/Linked List Cycle II.java, Problems & Solutions/142. Linked List Cycle II/09 March 2023/README.md, Problems & Solutions/875. Koko Eating Bananas/08 March 2023/Koko Eating Bananas.java, Problems & Solutions/875. Koko Eating Bananas/08 March 2023/README.md
Closes #384 
Closes #385 
Closes #386 
Closes #387
=> 08 & 09 March 2023

Problems & Solutions/382. Linked List Random Node/10 March 2023/Linked List Random Node.java, Problems & Solutions/382. Linked List Random Node/10 March 2023/README.md
=> 10 March 2023

Problems & Solutions/109. Convert Sorted List to Binary Search Tree/11 March 2023/Convert Sorted List to Binary Search Tree.java, Problems & Solutions/109. Convert Sorted List to Binary Search Tree/11 March 2023/README.md
=> 11 March 2023

Problems & Solutions/23. Merge k Sorted Lists/12 March 2023/Merge k Sorted Lists.java, Problems & Solutions/23. Merge k Sorted Lists/12 March 2023/README.md
=> 12 March 2023

Problems & Solutions/129. Sum Root to Leaf Numbers/14 March 2023/README.md, Problems & Solutions/129. Sum Root to Leaf Numbers/14 March 2023/Sum Root to Leaf Numbers.cpp
=> 14 March 2023

Problems & Solutions/106. Construct Binary Tree from Inorder and Postorder Traversal/16 March 2023/Construct Binary Tree from Inorder and Postorder Traversal.java, Problems & Solutions/106. Construct Binary Tree from Inorder and Postorder Traversal/16 March 2023/README.md, Problems & Solutions/958. Check Completeness of a Binary Tree/15 March 2023/Check Completeness of a Binary Tree.java, Problems & Solutions/958. Check Completeness of a Binary Tree/15 March 2023/README.md
Closes #401 
Closes #402 
Closes #403 
Closes #404
=> 15 & 16 March 2023

Problems & Solutions/1472. Design Browser History/18 Match 2023/Design Browser History.java, Problems & Solutions/1472. Design Browser History/18 Match 2023/README.md, Problems & Solutions/208. Implement Trie (Prefix Tree)/17 March 2023/Implement Trie (Prefix Tree).java, Problems & Solutions/208. Implement Trie (Prefix Tree)/17 March 2023/README.md
Closes #406 
Closes #407 
Closes #408 
Closes #409
=> 17 & 18 March 2023

Problems & Solutions/605. Can Place Flowers/20 March 2023/Can Place Flowers.java, Problems & Solutions/605. Can Place Flowers/20 March 2023/README.md
=> 20 March 2023

Problems & Solutions/2348. Number of Zero-Filled Subarrays/21 March 2023/Number of Zero-Filled Subarrays.java, Problems & Solutions/2348. Number of Zero-Filled Subarrays/21 March 2023/README.md
=> 21 March 2023

CONTRIBUTING.md, Problems & Solutions/2492. Minimum Score of a Path Between Two Cities/22 March 2023/Minimum Score of a Path Between Two Cities.java, Problems & Solutions/2492. Minimum Score of a Path Between Two Cities/22 March 2023/README.md
Updated problem of the day & contributing.md
Closes #438 
Closes #439
=> 22 March 2023

Problems & Solutions/1466. Reorder Routes to Make All Paths Lead to the City Zero/24 March 2023/Reorder Routes to Make All Paths Lead to the City Zero.java
=> Create Reorder Routes to Make All Paths Lead to the City Zero.java

Problems & Solutions/2316. Count Unreachable Pairs of Nodes in an Undirected Graph/25 March 2023/Count Unreachable Pairs of Nodes in an Undirected Graph.java
=> Create Count Unreachable Pairs of Nodes in an Undirected Graph.java

Problems & Solutions/2360. Longest Cycle in a Graph/26 March 2023/Longest Cycle in a Graph.java
=> Create Longest Cycle in a Graph.java

Problems & Solutions/64. Minimum Path Sum/27 March 2023/Minimum Path Sum.java
=> Create Minimum Path Sum.java

Problems & Solutions/983. Minimum Cost For Tickets/28 March 2023/Minimum Cost For Tickets983. Minimum Cost For Tickets.java
=> Create Minimum Cost For Tickets983. Minimum Cost For Tickets.java

Problems & Solutions/1402. Reducing Dishes/29 March 2023/Reducing Dishes.java
=> Create Reducing Dishes.java
